### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by mainini** [fusepoolP3/p3-any23-transformer#2]
Please update the default port on which the transformer starts according to https://github.com/fusepoolP3/overall-architecture/blob/master/default-ports.md

**Comment by westei** [comment]
The next time please add the desired default port to the issues description. Because of the original title I was changing it to `8194` and not `8303` :(

**Comment by westei** [comment]
fixed with https://github.com/fusepoolP3/p3-any23-transformer/releases/tag/any23-transformer-1.0.7

**Comment by mainini** [comment]
Sorry for the inconvenience! At the time I first opened the issue, the reference document pointed to the "old new" default ports - which got only changed shortly after. This is the reason why I later changed the issue to be more generic without including any portnumbers directly into it ;-)
Anyway, thanks a lot for fix&release!
